name: voice_env
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - numpy
  - scipy
  - pandas
  - soundfile
  - matplotlib
  - jupyterlab
  - librosa
  - tqdm
  - pyyaml
  - pip:
      - webrtcvad
      - noisereduce
      - pydub
      - streamlit